<a href="https://colab.research.google.com/github/Inkyu-Yang356/deep-learning-practice/blob/main/250402_multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초 실습

## List to Numpy Array

In [24]:
import numpy as np

In [25]:
test = np.array([[1,2,3], [4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

### 문제1 : 아래 list 3개를 각각 행으로 갖는 배열을 생성하는 코드를 완성하고 배열의 크기를 print 하세요

In [26]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

arr = np.array([list1,list2,list3]) # Numpy 배열로 리스트 각 행으로 병합

print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## Reshape

In [27]:
arr16 = np.array(list(range(16))).reshape((4,4))
# 범위 0-15인 리스트의 배열을 4x4로 재형성
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 문제2 : 0부터 15까지의 숫자를 원소로 갖는 배열을 아래의 형태로 만드는 코드를 작성해보세요

In [28]:
# [[ 0,  1],
# [ 2,  3],
# [ 4,  5],
# [ 6,  7],
# [ 8,  9],
# [10, 11],
# [12, 13],
# [14, 15]]

arr16_reshaped = arr16.reshape(8, 2)    # 8행 2열 재형성
print(arr16_reshaped)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


## 0 or 1 값 채우기

In [29]:
filled_one = np.ones(16)  # 1차원 배열 16개의 1 나열
filled_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
filled_zero = np.zeros((2,5)) # 2행 5열 0 으로 채우기
filled_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
filled_like_arr16 = np.ones_like(arr16)  # 같은 형태의 배열을 1로 채우기
filled_like_arr16

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 문제 3 : 아래 형태를 갖는 배열을 만드는 코드를 작성해보세요
- ones, zeros, reshape 사용
- 성공했으면 concatenate의 axis를 0으로 바꿔보고 어떤 동작을 하는지 적어보세요

In [32]:
# arr_with_one 배열 참고
# [[1., 1.],
# [1., 1.],
# [1., 1.],
# [1., 1.]]

# arr_with_zero 배열 참고
# [[0., 0.],
# [0., 0.],
# [0., 0.],
# [0., 0.]]

# arr_with_one_zero 배열 참고
# [[1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.]]

arr_with_one = np.ones(8).reshape(4,2)    # 4행 2열 재형성
arr_with_zero = np.zeros(8).reshape(4,2)  # 4행 2열 재형성
arr_with_one_zero = np.concatenate((arr_with_one, arr_with_zero), axis=1) # 수평으로 배열 합치기, Must have the same shape
arr_with_one_zero

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## Broadcasting

In [33]:
bc = np.ones(25).reshape((5,5))
bc = bc * 5 - 1  # Numpy를 통한 배열 연산
bc

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [34]:
bc2 = bc * 0 + 3  # threes 배열
bc + bc2    # fours + threes 배열 대 배열 연산

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [35]:
one_dim_arr = [5, 5, 5, 5, 5]
new_bc = bc + one_dim_arr  # 배열 대 배열 연산
new_bc

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

## Slicing

In [48]:
print(arr16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [37]:
arr16[2]  # 인덱스 2 행 조회

array([ 8,  9, 10, 11])

In [38]:
arr16[2,:]  # 인덱스 2행 전체 조회; 2차원

array([ 8,  9, 10, 11])

In [39]:
arr16[:,2]  # 인덱스 2열 전체 조회

array([ 2,  6, 10, 14])

In [40]:
print(arr16[0:2]) # 인덱스 0과 1행 조회; 2개의 행
print(arr16[0,2]) # 인덱스 0행 2열 조회; 1개의 셀

[[0 1 2 3]
 [4 5 6 7]]
2


In [41]:
arr16[1:3]  # 인덱스 1, 2행 조회

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr16[arr16[:,0]<5] # 인덱스 0열 중 5보다 작은 경우, 행 전체 다시 대입

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 문제 4 : 3번째 열에서(index=2) 10보다 크거나 같은 원소가 있는 행 전체를 담는 배열을 생성해보세요

In [49]:
# 결과
# [ 8,  9, 10, 11],
# [12, 13, 14, 15]]

test_arr = arr16[arr16[:, 2] >= 10]  # 2열 중 10보다 큰 경우, 해당 행 전체 재 대입
test_arr

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 평균(mean)

In [51]:
target = np.ones((10000,100))   # 행 10000, 열 100
target.shape

(10000, 100)

In [52]:
mean = target.mean(axis=0)    # axis=0; 각 행 평균
print(mean.shape)
print(mean)

(100,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [53]:
mean = target.mean(axis=1)    # axis=1; 각 열 평균
print(mean.shape)
print(mean)

(10000,)
[1. 1. 1. ... 1. 1. 1.]


# 코드를 통해서 XOR 문제 해결하기

In [54]:
# 가중치와 바이어스
w11 = np.array([-2, -2])
w12 = np.array([2, 2])
w2 = np.array([1, 1])

b1 = 3
b2 = -1
b3 = -1

In [55]:
# 퍼셉트론
def MLP(x, w, b):
    y = np.sum(w * x) + b

    if y <= 0:
        return 0
    else:
        return 1

In [56]:
# NAND 게이트 (은닉층)
def NAND(x1,x2):
    return MLP(np.array([x1, x2]), w11, b1) # np.sum(-2x)+3; [1,1] 일 경우 X

# OR 게이트   (은닉층)
def OR(x1,x2):
    return MLP(np.array([x1, x2]), w12, b2) # np.sum(2x)-1; [0,0] 일 경우 X

# AND 게이트
def AND(x1,x2):
    return MLP(np.array([x1, x2]), w2, b3)  # np.sum(x)-1; [1,1] 일 경우만 O

# XOR 게이트
def XOR(x1,x2):
    return AND(NAND(x1, x2),OR(x1,x2))    # NAND, OR이 모두 만족할 경우 [0,1], [1,0]
'''              AND (NAND, OR)
              1   0   => 0
              1   1   => 1
              1   1   => 1
              0   1   => 0
'''

In [57]:
# x1, x2 값을 번갈아 대입해 가며 최종 값 출력
for x in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = XOR(x[0], x[1])
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 0
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0


# Multi Perceptron Class 생성을 통해 해결하기

In [62]:
# XOR 문제를 해결하기 위한 다층 퍼셉트론
class SimpleMLP:
    def __init__(self):
        # 수동으로 설정한 가중치와 바이어스, 은닉층
        self.weights_input_hidden = np.array([[-2, 2], [-2, 2]])  # x1, x2 -> n1, n2 계산을 위한 가중치 배열
        self.bias_hidden = np.array([3, -1])  # x1, x2 -> n1, n2

        # 출력층: 1개의 뉴런
        self.weights_hidden_output = np.array([1, 1])  # n1, n2 -> y 가중치
        self.bias_output = -1  # n1, n2 -> y 바이어스

    def forward(self, X):
        # 은닉층 계산
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden    # dot 행렬의 곱
        hidden_output = np.where(hidden_input <= 0, 0, 1)   # where(data = 0 만족하면 0, 그렇지 않으면 1)
        print(f"hidden_output : {hidden_input}")

        # 출력층 계산
        final_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output    #  dot 행렬의 곱
        final_output = np.where(final_input <= 0, 0, 1)   # where(data = 0 만족하면 0, 그렇지 않으면 1)
        print(f"final_output : {final_input}")
        return final_output

'''
  w_11 w_12  =>  [-2, 2] ; b1 = 1
  w_21 w_22  =>  [-2, 2] ; b2 = 1

  [입력값] * [가중치] + 편향값
'''

IndentationError: unexpected indent (<ipython-input-62-bd25494fa87f>, line 15)

In [59]:
# XOR 데이터셋 정의
XOR_X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # 입력값
XOR_y = np.array([0, 1, 1, 0])  # XOR 출력값

In [60]:
# 모델 초기화
mlp = SimpleMLP()

In [61]:
# 예측
predictions = mlp.forward(XOR_X)
# 결과 출력
print(f"XOR 문제 예측 결과: {predictions}")

hidden_output : [[ 3 -1]
 [ 1  1]
 [ 1  1]
 [-1  3]]
final_output : [0 1 1 0]
XOR 문제 예측 결과: [0 1 1 0]
